/******************************************************************************/
/******************************************************************************/

INSERT INTO `billing_contacuentas` VALUES ('1', 'ACTIVOS', '', '');
INSERT INTO `billing_contacuentas` VALUES ('2', 'PASIVOS', '', '');
INSERT INTO `billing_contacuentas` VALUES ('3', 'PATRIMONIO NETO', '', '');
INSERT INTO `billing_contacuentas` VALUES ('4', 'SECCION INGRESOS', '', '');
INSERT INTO `billing_contacuentas` VALUES ('5', 'SECCION COSTOS', '', '');
INSERT INTO `billing_contacuentas` VALUES ('6', 'SECCION GANACIAS CONTINUADAS', '', '');
INSERT INTO `billing_contacuentas` VALUES ('7', 'SECCION GANACIAS DISCONTINUADAS', '', '');
INSERT INTO `billing_contacuentas` VALUES ('8', 'OTRO RESULTADO INTEGRAL', '', '');
INSERT INTO `billing_contacuentas` VALUES ('9', 'TOTAL AJUSTES POR CONVERSION', '', '');


/*INGRESAR EL PLAN DE CUENTAS COMPLETO*/
INSERT INTO `billing_contacuentasplan` VALUES ('1', 'ACTIVO', NULL, '', '1', '0', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101', 'ACTIVO CORRIENTE', '', NULL, '1', '1', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10101', 'EFECTIVO Y EQUIVALENTES AL EFECTIVO', '', '', '1', '101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010101', 'CAJA GENERAL', NULL, NULL, '1', '10101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101010101', 'Caja', NULL, NULL, '1', '1010101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101010102', 'Fondo Rotativo 1', NULL, NULL, '1', '1010101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101010103', 'Fondo Rotativo 2', NULL, NULL, '1', '1010101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010102', 'BANCOS', NULL, NULL, '1', '10101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101010201', 'Banco A', NULL, NULL, '1', '1010102', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101010202', 'Banco B', NULL, NULL, '1', '1010102', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101010203', 'Banco C', NULL, NULL, '1', '1010102', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101010204', 'BANCO D', NULL, NULL, '1', '1010102', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010103', 'Otros Efectivo y sus Equivalentes', NULL, NULL, '1', '10101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10102', 'ACTIVOS FINANCIEROS', '', '', '1', '101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010201', 'ACTIVOS FINANCIEROS A VALOR RAZONABLE CON CAMBIOS EN RESULTADOS', '', NULL, '1', '10102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010202', 'ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA', '', '', '1', '10102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010203', 'ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO', '', '', '1', '10102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010204', '(-) PROVISION POR DETERIORO', '', '', '1', '10102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010205', 'DOCUMENTOS Y CUENTAS POR COBRAR CLIENTES NO RELACIONADOS', '', '', '1', '10102', 0, 0);
INSERT INTO `billing_contacuentasplan` VALUES ('101020501', 'Cuentas por Cobrar Clientes No Relacionados', NULL, NULL, '1', '1010205', 1, 0);
INSERT INTO `billing_contacuentasplan` VALUES ('1010206', 'DOCUMENTOS Y CUENTAS POR COBRAR CLIENTES RELACIONADOS', '', '', '1', '10102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101020601', 'Cuentas por Cobrar Clientes Relacionados', NULL, NULL, '1', '1010206', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10102060101', 'Cuentas por Cobrar Clientes ', NULL, NULL, '1', '1010206', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10102060102', 'Tarjetas de Credito en Custodio', NULL, NULL, '1', '1010206', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10102060103', 'Cheques en Custodio', NULL, NULL, '1', '1010206', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010207', 'OTRAS CUENTAS POR COBRAR RELACIONADAS', '', '', '1', '10102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101020701', 'Cuentas por Cobrar Empleados', NULL, NULL, '1', '1010207', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101020702', 'Anticipos Empleados', NULL, NULL, '1', '1010207', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010208', 'OTRAS CUENTAS POR COBRAR', '', '', '1', '10102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101020801', 'Cuentas por Cobrar Accionista A', NULL, NULL, '1', '1010208', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101020802', 'Cuentas por Cobrar Accionista B', NULL, NULL, '1', '1010208', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010209', '(-) PROVISIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN CUENTAS INCOBRABLES', '', '', '1', '10102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10103', 'INVENTARIOS', '', '', '1', '101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010301', 'Inventarios de Materia Prima', '', '', '1', '10103', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010302', 'Inventario de Productos en Proceso', '', '', '1', '10103', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010303', 'Inventario de Suministros o Materiales a ser Consumidos en el  Prodeso de Produccion', NULL, '', '1', '10103', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010304', 'Inventarios de Suministros o Materiales a ser Consumidos en la Prestacion de Servicios', '', '', '1', '10103', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010305', 'Inventario de Prod. Term. y  Mercad. en almacen - Producido por la Cia.', '', '', '1', '10103', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010306', 'Inventarios de Prod. Term. y Mercad. en Almacen- Compradoi a Terceros', '', '', '1', '10103', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010307', 'Mercaderias en Transito', '', '', '1', '10103', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010308', 'Obras en Construccion', '', '', '1', '10103', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010309', 'Inventario Repuestos, Herramientas y accesorios', '', '', '1', '10103', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010310', 'Otros Inventarios', '', '', '1', '10103', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010311', '(-) Provision de Inventarios por Valor Neto de Realizacion', '', '', '1', '10103', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010312', '(-) Provision de Inventarios por deterioro', '', '', '1', '10103', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10104', 'SERVICIOS Y OTROS PAGOS ANTICIPADOS', '', '', '1', '101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010401', 'Seguros Pagados por Anticipado', '', '', '1', '10104', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010402', 'Arriendos PAgados por Anticipado.', '', '', '1', '10104', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010403', 'Anticipos a Proveedores', '', '', '1', '10104', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010404', 'Otros Anticipos Entregados', '', '', '1', '10104', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10105', 'ACTIVOS POR IMPUESTOS CORRIENTES', '', '', '1', '101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010501', 'CRÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°DITO TRIBUTARIO A FAVOR DE LA EMPRESA (IVA)', '', '', '1', '10105', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101050101', 'IVA en Compras', NULL, NULL, '1', '1010501', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101050102', 'Ret iva en Ventas.', NULL, NULL, '1', '1010501', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010502', 'CRÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°DITO TRIBUTARIO A FAVOR DE LA EMPRESA ( I. R.)', '', '', '1', '10105', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101050201', 'Credito Tributario I.R aÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â±os Anteriores', NULL, NULL, '1', '1010502', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101050202', 'Retencion Impuesto a la Renta en Ventas', NULL, NULL, '1', '1010502', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101050203', 'Otros', NULL, NULL, '1', '1010502', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010503', 'ANTICIPO DE IMPUESTO A LA RENTA', '', '', '1', '10105', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('101050301', 'Anticipo de Impuesto a la Renta', NULL, NULL, '1', '1010503', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10106', 'ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA Y OPERACIONES DISCONTINUADAS', '', '', '1', '101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10107', 'OTROS ACTIVOS CORRIENTES', '', '', '1', '101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1010701', 'Otros Activos Corrientes', NULL, NULL, '1', '10107', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('102', 'ACTIVO NO CORRIENTE', '', '', '1', '1', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10201', 'PROPIEDADES, PLANTA Y EQUIPO', '', '', '1', '102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020101', 'Terrenos', '', '', '1', '10201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020102', 'Edificios', '', '', '1', '10201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020103', 'Construcciones en Curso', '', '', '1', '10201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020104', 'Instalaciones', '', '', '1', '10201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020105', 'Muebles y Enseres', '', '', '1', '10201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020106', 'Maquinaria y Equipo', '', '', '1', '10201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020107', 'Naves, Aeronaves, Barcazas y Similares', '', '', '1', '10201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020108', 'Equipo de Computacion', '', '', '1', '10201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020109', 'Vehiculos, Equipos de Transporte y Equipo Caminero Movil', '', '', '1', '10201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020110', 'Otros Propiedades Planta y Equipos', '', '', '1', '10201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020111', 'Repuestos y Herramientas', '', '', '1', '10201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020112', '(-) DEPRECIACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN ACUMULADA PROPIEDADES, PLANTA Y EQUIPO', '', '', '1', '10201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('102011201', '(-) Dep. Acum. Edificios', NULL, NULL, '1', '1020112', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('102011202', '(-) Dep. Acum. Instalaciones', NULL, NULL, '1', '1020112', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('102011203', '(-) Dep. Acum. Muebles y Enseres', NULL, NULL, '1', '1020112', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('102011204', '(-) Dep. Acum.Maquinaria y Equipo', NULL, NULL, '1', '1020112', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('102011205', '(-) Dep. Acum. Naves Aeronaves y Barcazas y Similares', NULL, NULL, '1', '1020112', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('102011206', '(-) Dep. Acum.Equipos de Computacion', NULL, NULL, '1', '1020112', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('102011207', '(-) Dep. Acum. Otros Propiedad Planta y Equipo', NULL, NULL, '1', '1020112', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020113', '(-) DETERIORO  ACUMULADO DE PROPIEDADES, PLANTA Y EQUIPO', '', '', '1', '10201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020114', 'ACTIVOS DE EXPLORACION Y EXPLOTACION', '', '', '1', '10201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('102011401', 'Activos de Exploracion y Explotacion', '', '', '1', '1020114', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('102011402', '(-) Amortizacion Acumulada de Activos de Exploracion y Explotacion', '', '', '1', '1020114', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('102011403', '(-) Deterioro Acumulado de Activos de Exploracion y Explotacion', '', '', '1', '1020114', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10202', 'PROPIEDADES DE INVERSIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN', '', '', '1', '102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020201', 'Terrenos (Propiedades de Inversion)', '', '', '1', '10202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020202', 'Edificios (Propiedades de Inversion)', '', '', '1', '10202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020203', '(-) DEPRECIACION ACUMULADA DE PROPIEDADES DE INVERSIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN', '', '', '1', '10202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020204', '(-) DETERIORO ACUMULADO DE PROPIEDADES DE INVERSIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN', '', '', '1', '10202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10203', 'ACTIVOS BIOLOGICOS', '', '', '1', '102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020301', 'ANIMALES VIVOS EN CRECIMIENTO', '', '', '1', '10203', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020302', 'ANIMALES VIVOS EN PRODUCCION', '', '', '1', '10203', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020303', 'PLANTAS EN CRECIMIENTO', '', '', '1', '10203', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020304', 'PLANTAS EN PRODUCCION', '', '', '1', '10203', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020305', '(-) DEPRECIACION ACUMULADA DE ACTIVOS BIOLÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œGICOS', '', '', '1', '10203', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020306', '(-) DETERIORO ACUMULADO DE ACTIVOS BIOLOGÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚ÂCOS', '', '', '1', '10203', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10204', 'ACTIVO INTANGIBLE', '', '', '1', '102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020401', 'Plusvalias', '', '', '1', '10204', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020402', 'Marcas, Patentes, Derechos de llave , Cuotas Patrimoniales y Otros Similares', '', '', '1', '10204', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020403', 'ACTIVOS DE EXPLORACION Y EXPLOTACION', '', '', '1', '10204', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020404', '(-) AMORTIZACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN ACUMULADA DE ACTIVOS INTANGIBLE', '', '', '1', '10204', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020405', '(-) DETERIORO ACUMULADO DE ACTIVO INTANGIBLE', '', '', '1', '10204', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020406', 'OTROS INTANGIBLES', '', '', '1', '10204', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10205', 'ACTIVOS POR IMPUESTOS DIFERIDOS', '', '', '1', '102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020501', 'Activos por Impuestos Diferidos', '', '', '1', '10205', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10206', 'ACTIVOS FINANCIEROS NO CORRIENTES', '', '', '1', '102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020601', 'ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO', '', '', '1', '10206', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020602', '(-) PROVISION POR DETERIORO DE ACTIVOS FINANCIEROS MANTENIDOS HASTA EL VENCIMIENTO', '', '', '1', '10206', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020603', 'DOCUMENTOS Y CUENTAS POR COBRAR L/P', '', '', '1', '10206', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('102060301', 'Cheques en Garantia', NULL, NULL, '1', '1020603', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020604', '(-) PROVISIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN CUENTAS INCOBRABLES DE ACTIVOS FINANCIEROS NO CORRIENTES', '', '', '1', '10206', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('10207', 'OTROS ACTIVOS NO CORRIENTES', '', '', '1', '102', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020701', 'INVERSIONES SUBSIDIARIAS', '', '', '1', '10207', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020702', 'INVERSIONES ASOCIADAS', '', '', '1', '10207', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020703', 'INVERSIONES NEGOCIOS CONJUNTOS', '', '', '1', '10207', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020704', 'OTRAS INVERSIONES', '', '', '1', '10207', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020705', '(-) PROVISIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN VALUACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â', '', '', '1', '10207', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('1020706', 'OTROS ACTIVOS NO CORRIENTES', '', '', '1', '10207', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2', 'PASIVO', '', '', '2', '0', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201', 'PASIVO CORRIENTE', '', '', '2', '2', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20101', 'PASIVOS FINANCIEROS A VALOR RAZONABLE CON CAMBIOS EN RESULTADOS', '', '', '2', '201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20102', 'PASIVOS POR CONTRATOS DE ARRENDAMIENTO FINANCIEROS', '', '', '2', '201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20103', 'CUENTAS Y DOCUMENTOS POR PAGAR', '', '', '2', '201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010301', 'LOCALES', '', '', '2', '20103', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201030101', 'Cuentas por Pagar Proveedores Locales', NULL, NULL, '2', '2010301', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010302', 'DEL EXTERIOR', '', '', '2', '20103', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201030201', 'Cuentas por Pagar Proveedores Exterior', NULL, NULL, '2', '2010302', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20104', 'OBLIGACIONES CON INSTITUCIONES FINANCIERAS', '', '', '2', '201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010401', 'LOCALES', '', '', '2', '20104', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201040101', 'Sobregiros Ocasionales IFIS', NULL, NULL, '2', '2010401', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201040102', 'Banco A por Pagar', NULL, NULL, '2', '2010401', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201040103', 'Banco B por Pagar', NULL, NULL, '2', '2010401', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201040104', 'Banco C por Pagar', NULL, NULL, '2', '2010401', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010402', 'DEL EXTERIOR', '', '', '2', '20104', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20105', 'PROVISIONES', '', '', '2', '201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010501', 'LOCALES', '', '', '2', '20105', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201050101', 'Provisiones A', NULL, NULL, '2', '2010501', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010502', 'DEL EXTERIOR', '', '', '2', '20105', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20106', 'PORCIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN CORRIENTE DE OBLIGACIONES EMITIDAS', '', '', '2', '201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010601', 'Porcion Corriente Prestamo Banco A', NULL, NULL, '2', '20106', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010602', 'Porcion Corriente Prestamo Banco B', NULL, NULL, '2', '20106', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20107', 'OTRAS OBLIGACIONES CORRIENTES', '', '', '2', '201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010701', 'CON LA ADMINISTRACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN TRIBUTARIA', '', '', '2', '20107', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201070101', 'Ret Fte por Pagar', NULL, NULL, '2', '2010701', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201070102', 'Ret IVA por Pagar', NULL, NULL, '2', '2010701', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201070103', 'IVA en Ventas', NULL, NULL, '2', '2010701', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201070104', 'Servicio de Rentas por Pagar', NULL, NULL, '2', '2010701', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010702', 'IMPUESTO A LA RENTA POR PAGAR DEL EJERCICIO', '', '', '2', '20107', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010703', 'CON EL IESS', '', '', '2', '20107', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201070301', 'IESS por Pagar', NULL, NULL, '2', '2010703', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010704', 'POR BENEFICIOS DE LEY A EMPLEADOS', '', '', '2', '20107', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201070401', 'Decimo Tercero por Pagar', NULL, NULL, '2', '2010704', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201070402', 'Decimo Cuarto por Pagar', NULL, NULL, '2', '2010704', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('201070403', 'Vacaciones por Pagar', NULL, NULL, '2', '2010704', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010705', 'Participacion Trabajadores por Pagar del Ejercicio', '', '', '2', '20107', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010706', 'Dividendos por Pagar', '', '', '2', '20107', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20108', 'CUENTAS POR PAGAR DIVERSAS RELACIONADAS', '', '', '2', '201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010801', 'Cuentas por Pagar Accionista A', NULL, NULL, '2', '20108', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2010802', 'Cuentas por Pagar Accionista B', NULL, NULL, '2', '20108', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20109', 'OTROS PASIVOS FINANCIEROS', '', '', '2', '201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20110', 'ANTICIPOS DE CLIENTES', '', '', '2', '201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20111', 'PASIVOS DIRECTAMENTE ASOCIADOS CON LOS ACTIVOS NO CORRIENTES Y OPERACIONES DISCONTINUADAS', '', '', '2', '201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20112', 'PORCION CORRIENTE DE PROVISIONES POR BENEFICIOS A EMPLEADOS', '', '', '2', '201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2011201', 'Jubilacion Patronal', '', '', '2', '20112', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2011202', 'Otros Beneficios a Largo Plazo para los Empleados', '', '', '2', '20112', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20113', 'OTROS PASIVOS CORRIENTES', '', '', '2', '201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('202', 'PASIVO NO CORRIENTE', '', '', '2', '2', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20201', 'PASIVOS POR CONTRATOS DE ARRENDAMIENTO FINANCIERO', '', '', '2', '202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20202', 'CUENTAS Y DOCUMENTOS POR PAGAR L/P', '', '', '2', '202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2020201', 'LOCALES', '', '', '2', '20202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2020202', 'DEL EXTERIOR', '', '', '2', '20202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20203', 'OBLIGACIONES CON INSTITUCIONES FINANCIERAS', '', '', '2', '202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2020301', 'LOCALES', '', '', '2', '20203', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('202030101', 'Prestamo Banco A largo PLazo', NULL, NULL, '2', '2020301', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('202030102', 'Prestamo Banco B largo PLazo', NULL, NULL, '2', '2020301', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2020302', 'DEL EXTERIOR', '', '', '2', '20203', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20204', 'CUENTAS POR PAGAR DIVERSAS/RELACIONADAS', '', '', '2', '202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2020401', 'LOCALES', '', '', '2', '20204', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2020402', 'DEL EXTERIOR', '', '', '2', '20204', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20205', 'OBLIGACIONES EMITIDAS', '', '', '2', '202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20206', 'ANTICIPOS DE CLIENTES', '', '', '2', '202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20207', 'PROVISIONES POR BENEFICIOS A EMPLEADOS', '', '', '2', '202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2020701', 'JUBILACION PATRONAL', '', '', '2', '20207', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2020702', 'OTROS BENEFICIOS NO CORRIENTES PARA LOS EMPLEADOS', '', '', '2', '20207', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20208', 'OTRAS PROVISIONES', '', '', '2', '202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20209', 'PASIVO DIFERIDO', '', '', '2', '202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2020901', 'Ingresos Diferidos', '', '', '2', '20209', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('2020902', 'Pasivos por Impuestos Diferidos', '', '', '2', '20209', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('20210', 'OTROS PASIVOS NO CORRIENTES', '', '', '2', '202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('3', 'PATRIMONIO NETO', '', '', '3', '1', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('301', 'CAPITAL', '', '', '3', '3', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30101', 'CAPITAL SUSCRITO o  ASIGNADO', '', '', '3', '301', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('3010101', 'Socio A Cta Capital', NULL, NULL, '3', '30101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('3010102', 'Socio B Cta Capital', NULL, NULL, '3', '30101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('3010103', 'Socio C Cta Capital', NULL, NULL, '3', '30101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30102', '(-) CAPITAL SUSCRITO NO PAGADO, ACCIONES EN TESORERÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚ÂA', '', '', '3', '301', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('302', 'APORTES DE SOCIOS O ACCIONISTAS PARA FUTURA CAPITALIZACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN', '', '', '3', '3', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('303', 'PRIMA POR EMISIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN PRIMARIA DE ACCIONES', '', '', '3', '3', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('304', 'RESERVAS', '', '', '3', '3', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30401', 'RESERVA LEGAL', '', '', '3', '304', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30402', 'RESERVAS FACULTATIVA Y ESTATUTARIA', '', '', '3', '304', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30403', 'RESERVA DE CAPITAL', '', '', '3', '304', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30404', 'OTRAS RESERVAS', '', '', '3', '304', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('305', 'OTROS RESULTADOS INTEGRALES', '', '', '3', '3', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30501', 'SUPERAVIT DE ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA', '', '', '3', '305', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30502', 'SUPERAVIT POR REVALUACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN DE PROPIEDADES, PLANTA Y EQUIPO', '', '', '3', '305', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30503', 'SUPERAVIT POR REVALUACION DE ACTIVOS INTANGIBLES', '', '', '3', '305', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30504', 'OTROS SUPERAVIT POR REVALUACION', '', '', '3', '305', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('306', 'RESULTADOS ACUMULADOS', '', '', '3', '3', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30601', 'GANANCIAS ACUMULADAS', '', '', '3', '306', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30602', '(-) PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°RDIDAS ACUMULADAS', '', '', '3', '306', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30603', 'RESULTADOS ACUMULADOS PROVENIENTES DE LA ADOPCION POR PRIMERA VEZ DE LAS NIIF', '', '', '3', '306', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('307', 'RESULTADOS DEL EJERCICIO', '', '', '3', '3', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30701', 'GANANCIA NETA DEL PERIODO', '', '', '3', '307', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('30702', '(-) PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°RDIDA NETA DEL PERIODO', '', '', '3', '307', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4', 'SECCION INGRESOS', '', '', '4', '1', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('41', 'INGRESOS DE ACTIVIDADES ORDINARIAS', '', '', '4', '4', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4101', 'VENTA DE BIENES', '', '', '4', '41', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4102', 'PRESTACION DE SERVICIOS', '', '', '4', '41', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4103', 'CONTRATOS DE CONSTRUCCION', '', '', '4', '41', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4104', 'SUBVENCIONES DEL GOBIERNO', '', '', '4', '41', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4105', 'REGALÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚ÂAS', '', '', '4', '41', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4106', 'INTERESES', '', '', '4', '41', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('410601', 'cuenta no vale', NULL, NULL, '4', '4106', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4107', 'DIVIDENDOS', '', '', '4', '41', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4108', 'OTROS INGRESOS DE ACTIVIDADES ORDINARIAS', '', '', '4', '41', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4109', '(-) DESCUENTO EN VENTAS', '', '', '4', '41', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4110', '(-) DEVOLUCIONES EN VENTAS', '', '', '4', '41', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4111', '(-) BONIFICACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN EN PRODUCTO', '', '', '4', '41', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4112', '(-) OTRAS REBAJAS COMERCIALES', '', '', '4', '41', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('42', 'GANANCIA BRUTA', 'A', '(41 - 51)', '4', '4', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('43', 'OTROS INGRESOS', '', '', '4', '4', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4301', 'DIVIDENDOS', '', '', '4', '43', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4302', 'INTERESES FINANCIEROS', '', '', '4', '43', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4303', 'GANANCIA EN INVERSIONES EN ASOCIADAS / SUBSIDIARIAS Y OTRAS', '', '', '4', '43', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4304', 'VALUACION DE INSTRUMENTOS FINANCIEROS A VALOR RAZONABLE CON CAMBIO EN RESULTADOS', '', '', '4', '43', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('4305', 'OTRAS RENTAS', '', '', '4', '43', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('5', 'SECCION COSTOS', '', '', '5', '1', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('51', 'COSTO DE VENTAS Y PRODUCCION', '', '', '5', '5', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('5101', 'MATERIALES UTILIZADOS O PRODUCTOS VENDIDOS', '', '', '5', '51', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510101', '(+) INVENTARIO INICIAL DE BIENES NO PRODUCIDOS POR LA COMPAÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¹Ãƒâ€¦Ã¢â‚¬Å“IA', '', '', '5', '5101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510102', '(+) COMPRAS NETAS LOCALES DE BIENES NO PRODUCIDOS POR LA COMPAÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¹Ãƒâ€¦Ã¢â‚¬Å“IA', '', '', '5', '5101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510103', '(+) IMPORTACIONES DE BIENES NO PRODUCIDOS POR LA COMPAÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¹Ãƒâ€¦Ã¢â‚¬Å“IA', '', '', '5', '5101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510104', '(-) INVENTARIO FINAL DE BIENES NO PRODUCIDOS POR LA COMPAÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¹Ãƒâ€¦Ã¢â‚¬Å“IA', '', '', '5', '5101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510105', '(+) INVENTARIO INICIAL DE MATERIA PRIMA', '', '', '5', '5101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510106', '(+) COMPRAS NETAS LOCALES DE MATERIA PRIMA', '', '', '5', '5101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510107', '(+) IMPORTACIONES DE MATERIA PRIMA', '', '', '5', '5101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510108', '(-) INVENTARIO FINAL DE MATERIA PRIMA', '', '', '5', '5101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510109', '(+) INVENTARIO INICIAL DE PRODUCTOS EN PROCESO', '', '', '5', '5101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510110', '(-) INVENTARIO FINAL DE PRODUCTOS EN PROCESO', '', '', '5', '5101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510111', '(+) INVENTARIO INICIAL PRODUCTOS TERMINADOS', '', '', '5', '5101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510112', '(-) INVENTARIO FINAL DE PRODUCTOS TERMINADOS', '', '', '5', '5101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('5102', '(+) MANO DE OBRA DIRECTA', '', '', '5', '51', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510201', 'SUELDOS Y BENEFICIOS SOCIALES', '', '', '5', '5102', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('51020101', 'Sueldo Personal (Produccion)', NULL, NULL, '5', '510201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('51020102', 'Decimo Tercero (Produccion)', NULL, NULL, '5', '510201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('51020103', 'Decimo Cuarto (Produccion)', NULL, NULL, '5', '510201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('51020104', 'Vacaciones (Produccion)', NULL, NULL, '5', '510201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('51020105', 'Horas Extras (Produccion)', NULL, NULL, '5', '510201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('51020106', 'Comisiones(Produccion)', NULL, NULL, '5', '510201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('51020107', 'Bonoficaciones (Produccion)', NULL, NULL, '5', '510201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('51020108', 'Fondos de Reserva Pesonal (Produccion)', NULL, NULL, '5', '510201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510202', 'GASTO PLANES DE BENEFICIOS A EMPLEADOS', '', '', '5', '5102', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('5103', '(+) MANO DE OBRA INDIRECTA', '', '', '5', '51', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510301', 'SUELDOS Y BENEFICIOS SOCIALES', '', '', '5', '5103', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510302', 'GASTO PLANES DE BENEFICIOS A EMPLEADOS', '', '', '5', '5103', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('5104', '(+) OTROS COSTOS INDIRECTOS DE FABRICACION', '', '', '5', '51', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510401', 'DEPRECIACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN PROPIEDADES, PLANTA Y EQUIPO', '', '', '5', '5104', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510402', 'DEPRECIACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN DE ACTIVOS BIOLOGICOS', '', '', '5', '5104', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510403', 'DETERIORO DE PROPIEDAD, PLANTA Y EQUIPO', '', '', '5', '5104', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510404', 'EFECTO VALOR NETO DE REALIZACION DE INVENTARIOS', '', '', '5', '5104', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510405', 'GASTO POR GARANTIAS EN VENTA DE PRODUCTOS O SERVICIOS', '', '', '5', '5104', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510406', 'MANTENIMIENTO Y REPARACIONES', '', '', '5', '5104', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510407', 'SUMINISTROS MATERIALES Y REPUESTOS', '', '', '5', '5104', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('510408', 'OTROS COSTOS DE PRODUCCIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN', '', '', '5', '5104', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52', 'GASTOS', '', '', '5', '5', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('5201', 'GASTOS DE VENTA', '', '', '5', '52', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520101', 'SUELDOS, SALARIOS Y DEMÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚ÂS REMUNERACIONES', '', '', '5', '5201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52010101', 'Sueldo Personal (Ventas)', NULL, NULL, '5', '520101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52010102', 'Decimo Tercero (Ventas)', NULL, NULL, '5', '520101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52010103', 'Decimo Cuarto (Ventas)', NULL, NULL, '5', '520101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52010104', 'Vacaciones (Ventas)', NULL, NULL, '5', '520101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52010105', 'Horas Extras (Ventas)', NULL, NULL, '5', '520101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52010106', 'Comisiones (Ventas)', NULL, NULL, '5', '520101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52010107', 'Bonificaciones Personal (Ventas)', NULL, NULL, '5', '520101', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52010108', 'nnn', NULL, NULL, '5', '520101', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520102', 'APORTES A LA SEGURIDAD SOCIAL (incluido fondo de reserva)', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52010201', 'Aporte Patronal 12.15 (Ventas)', NULL, NULL, '5', '520102', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52010202', 'Fondos de Reserva Pesonal (Ventas)', NULL, NULL, '5', '520102', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520103', 'BENEFICIOS SOCIALES E INDEMNIZACIONES', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52010301', 'Indemnizaciones personal (ventas)', NULL, NULL, '5', '520103', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520104', 'GASTO PLANES DE BENEFICIOS A EMPLEADOS', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520105', 'Honorarios Comisiones Dietas Personas Naturales ( Ventas)', '', '', '5', '5201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520106', 'Remuneraciones a Otros Trabajadores Autonomos ( Ventas )', '', '', '5', '5201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520107', 'Honorarios a Extranjeros por Servicios  Ocasionales ', '', '', '5', '5201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520108', 'MANTENIMIENTO Y REPARACIONES', '', '', '5', '5201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520109', 'ARRENDAMIENTO OPERATIVO', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520110', 'COMISIONES', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520111', 'Promosion y Publicidad (Ventas)', '', '', '5', '5201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520112', 'Combustibles (Ventas)', '', '', '5', '5201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520113', 'Lubricantes ( Ventas)', '', '', '5', '5201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520114', 'Seguros Y Reaseguros (Ventas) (primas y cesiones)', '', '', '5', '5201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520115', 'TRANSPORTE', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52011501', 'Transporte de Carga', NULL, NULL, '5', '520115', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52011502', 'Transporte de Couriers', NULL, NULL, '5', '520115', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520116', 'Gastos de Gestion (Ventas) (agasajos a accionistas, trabajadores y clientes)', '', '', '5', '5201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520117', 'GASTOS DE VIAJE', '', '', '5', '5201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520118', 'AGUA, ENERGÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚ÂA, LUZ, Y TELECOMUNICACIONES', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52011801', 'Agua', NULL, NULL, '5', '520118', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52011802', 'Energia', NULL, NULL, '5', '520118', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52011803', 'Telecomunicaciones', NULL, NULL, '5', '520118', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52011804', 'Internet', NULL, NULL, '5', '520118', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('5201180401', 'Celular', NULL, NULL, '5', '52011804', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520119', 'Notarios y Registradores de la propie o Mercantiles', '', '', '5', '5201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520121', 'DEPRECIACIONES:', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52012101', 'PROPIEDADES, PLANTA Y EQUIPO', '', '', '5', '520121', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52012102', 'PROPIEDADES DE INVERSIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN', '', '', '5', '520121', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520122', 'AMORTIZACIONES:', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52012201', 'INTANGIBLES', '', '', '5', '520122', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52012202', 'OTROS ACTIVOS', '', '', '5', '520122', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520123', 'GASTO DETERIORO:', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52012301', 'PROPIEDADES, PLANTA Y EQUIPO', '', '', '5', '520123', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52012306', 'OTROS ACTIVOS', '', '', '5', '520123', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520124', 'GASTOS POR CANTIDADES ANORMALES DE UTILIZACION EN EL PROCESO DE PRODUCCIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN:', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52012401', 'MANO DE OBRA', '', '', '5', '520124', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52012402', 'MATERIALES', '', '', '5', '520124', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52012403', 'COSTOS DE PRODUCCION', '', '', '5', '520124', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520125', 'GASTO POR REESTRUCTURACION', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520126', 'VALOR NETO DE REALIZACION DE INVENTARIOS', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520127', 'OTROS GASTOS', '', '', '5', '5201', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('5202', 'GASTOS ADMINISTRATIVOS', '', '', '5', '52', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520201', 'SUELDOS, SALARIOS Y DEMÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚ÂS REMUNERACIONES', '', '', '5', '5202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52020101', 'Sueldos Personal (Administrativos)', NULL, NULL, '5', '520201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52020102', 'Decimo Tercero (Administrativos)', NULL, NULL, '5', '520201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52020103', 'Decimo Cuarto (Administrativos)', NULL, NULL, '5', '520201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52020104', 'Horas Extras (Administrativos)', NULL, NULL, '5', '520201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52020105', 'Comisiones (Administrativos)', NULL, NULL, '5', '520201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52020106', 'Bonificaciones (Administrativos)', NULL, NULL, '5', '520201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52020107', 'Fondos de Reserva (Administrativos)', NULL, NULL, '5', '520201', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520202', 'APORTES A LA SEGURIDAD SOCIAL (incluido fondo de reserva)', '', '', '5', '5202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52020201', 'Aporte Patronal 12.15 (Administrativo)', NULL, NULL, '5', '520202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52020202', 'Fondo de Reserva Personal (Administrativo)', NULL, NULL, '5', '520202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520203', 'BENEFICIOS SOCIALES E INDEMNIZACIONES', '', '', '5', '5202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520204', 'GASTO PLANES DE BENEFICIOS A EMPLEADOS', '', '', '5', '5202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520205', 'Honorarios Comisiones Dietas Personas Naturales (Administrativo)', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520206', 'Remuneraciones a Otros Trabajadores Autonomos ( Administrativos) )', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520207', 'Honorarios a Extranjeros por Servicios  Ocasionales (Administrativas)', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520208', 'MANTENIMIENTO Y REPARACIONES (Administrativos)', '', '', '5', '5202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52020801', 'Mantenimiento Edificios', NULL, NULL, '5', '520208', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52020802', 'Mantenimiento y Repartacion Equipos', NULL, NULL, '5', '520208', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52020803', 'Mantenimiento y Repartacion Vehiculos', NULL, NULL, '5', '520208', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520209', 'ARRENDAMIENTO OPERATIVO', '', '', '5', '5202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52020901', 'Arriendo local', NULL, NULL, '5', '520209', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520210', 'COMISIONES', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520212', 'Combustibles', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520213', 'Lubricantes', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520214', 'Seguros y Reaseguros (primas y cesiones)', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520215', 'TRANSPORTE (adminiistrativo)', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520216', 'Gastos de Gestion (Admin) (agasajos a accionistas, trabajadores y clientes)', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520217', 'GASTOS DE VIAJE', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520218', 'AGUA, ENERGÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚ÂA, LUZ, Y TELECOMUNICACIONES', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520219', 'NOTARIOS Y REGISTRADORES DE LA PROPIEDAD O MERCANTILES', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520220', 'IMPUESTOS, CONTRIBUCIONES Y OTROS', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520221', 'DEPRECIACIONES:', '', '', '5', '5202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52022101', 'PROPIEDADES, PLANTA Y EQUIPO', '', '', '5', '520221', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52022102', 'PROPIEDADES DE INVERSIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN', '', '', '5', '520221', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520222', 'AMORTIZACIONES:', '', '', '5', '5202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52022201', 'INTANGIBLES (Amortizaciones)', '', '', '5', '520222', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52022202', 'OTROS ACTIVOS (<amortizacion)', '', '', '5', '520222', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520223', 'GASTO DETERIORO:', '', '', '5', '5202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52022301', 'DETERIORO PROPIEDADES, PLANTA Y EQUIPO', '', '', '5', '520223', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52022302', 'DETERIORO INVENTARIOS', '', '', '5', '520223', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52022303', 'DETERIORO INSTRUMENTOS FINANCIEROS', '', '', '5', '520223', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52022304', 'DETERIORO INTANGIBLES', '', '', '5', '520223', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52022305', 'DETERIORO CUENTAS POR COBRAR', '', '', '5', '520223', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52022306', 'DETERIORO OTROS ACTIVOS', '', '', '5', '520223', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520224', 'GASTOS POR CANTIDADES ANORMALES DE UTILIZACION EN EL PROCESO DE PRODUCCIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN:', '', '', '5', '5202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52022401', 'MANO DE OBRA', '', '', '5', '520224', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52022402', 'MATERIALES', '', '', '5', '520224', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52022403', 'COSTOS DE PRODUCCION', '', '', '5', '520224', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520225', 'GASTO POR REESTRUCTURACION', '', '', '5', '5202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520226', 'VALOR NETO DE REALIZACION DE INVENTARIOS', '', '', '5', '5202', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520227', 'OTROS GASTOS', '', '', '5', '5202', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('5203', 'GASTOS FINANCIEROS', '', '', '5', '52', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520301', 'INTERESES', '', '', '5', '5203', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52030101', 'Intereses por prestamos, sobregiros', NULL, NULL, '5', '520301', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520302', 'COMISIONES', '', '', '5', '5203', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52030201', 'Comisiones Bancarias', NULL, NULL, '5', '520302', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('52030202', 'Comisiones Bancarias Tarjetas de Credito', NULL, NULL, '5', '520302', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520303', 'GASTOS DE FINANCIAMIENTO DE ACTIVOS', '', '', '5', '5203', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520304', 'DIFERENCIA EN CAMBIO', '', '', '5', '5203', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520305', 'OTROS GASTOS FINANCIEROS', '', '', '5', '5203', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('5204', 'OTROS GASTOS', '', '', '5', '52', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520401', 'PERDIDA EN INVERSIONES EN ASOCIADAS / SUBSIDIARIAS Y OTRAS', '', '', '5', '5204', 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('520402', 'OTROS', '', '', '5', '5204', 1, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('6', 'SECCION GANACIAS CONTINUADAS', '', '', '6', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('60', 'GANANCIA (PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°RDIDA) ANTES DE PARTICIPACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€š', 'B', '(A + 43 - 52)', '6', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('61', 'PARTICIPACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN TRABAJADORES', '', '', '6', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('62', 'GANANCIA (PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°RDIDA) ANTES DE IMPUESTOS', 'C', '(B-61)', '6', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('63', 'IMPUESTO A LA RENTA', '', '', '6', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('64', 'GANANCIA (PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°RDIDA) DE OPERACIONES CONTINUADAS', 'D', '(C-63)', '6', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('7', 'SECCION GANACIAS DISCONTINUADAS', '', '', '7', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('71', 'INGRESOS POR OPERACIONES DISCONTINUADAS', '', '', '7', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('72', 'GASTOS POR OPERACIONES DISCONTINUADAS', '', '', '7', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('73', 'GANANCIA (PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°RDIDA) ANTES DE PARTICIPACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€š', 'E', '(71-72)', '7', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('74', 'PARTICIPACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN TRABAJADORES', '', '', '7', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('75', 'GANANCIA (PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°RDIDA) ANTES DE IMPUESTOS DE OPERACIONES DISCONTINUADAS', 'F', '(E-74)', '7', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('76', 'IMPUESTO A LA RENTA', '', '', '7', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('77', 'GANANCIA (PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°RDIDA) DE OPERACIONES DISCONTINUADAS', 'G', '(F-76)', '7', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('79', 'GANANCIA (PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°RDIDA) NETA DEL PERIODO', 'H', '(D+G)', '7', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('8', 'OTRO RESULTADO INTEGRAL', '', '', '8', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('81', 'COMPONENTES DEL OTRO RESULTADO INTEGRAL', '', '', '8', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('8101', 'DIFERENCIA DE CAMBIO POR CONVERSIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN', '', '', '8', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('8102', 'VALUACION DE ACTIVOS FINANCIEROS DISPONIBLES PARA LA VENTA', '', '', '8', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('8103', 'GANANCIAS POR REVALUACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN DE PROPIEDADES, PLANTA  Y EQUIPO', '', '', '8', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('8104', 'GANANCIAS (PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°RDIDAS) ACTUARIALES POR PLANES DE BENEFICIOS DEFINIDOS', '', '', '8', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('8105', 'REVERSION DEL DETERIORO (PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°RDIDA POR DETERIORO) DE UN ACTIVO REVALUADO', '', '', '8', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('8106', 'PARTICIPACION DE OTRO RESULTADO INTEGRAL DE ASOCIADAS', '', '', '8', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('8107', 'IMPUESTO SOBRE LAS GANANCIAS RELATIVO A OTRO RESULTADO INTEGRAL', '', '', '8', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('8108', 'OTROS (DETALLAR EN NOTAS)', '', '', '8', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('82', 'RESULTADO INTEGRAL TOTAL DEL AÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¹Ãƒâ€¦Ã¢â‚¬Å“O', 'I', '(H + 81)', '8', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9', 'TOTAL AJUSTES POR CONVERSION', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('90', 'GANANCIA POR ACCION:', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9001', 'Ganancia por acciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n bÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¡sica', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('900101', 'Ganancia por acciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n bÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¡sica en operaciones continuadas', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('900102', 'Ganancia por acciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n bÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¡sica en operaciones discontinuadas', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9002', 'Ganancia por acciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n diluÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â­da', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('900201', 'Ganancia por acciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n diluÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â­da en operaciones continuadas', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('900202', 'Ganancia por acciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n diluÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â­da en operaciones discontinuadas', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('91', 'UTILIDAD A REINVERTIR (INFORMATIVO)', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('95', 'INCREMENTO NETO (DISMINUCIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN) EN EL EFECTIVO Y EQUIVALENTES AL EFECTIVO, ANTES DEL EFECTO DE LOS CAMBIOS EN LA TASA DE CAMBIO', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9501', 'FLUJOS DE EFECTIVO PROCEDENTES DE (UTILIZADOS EN) ACTIVIDADES DE OPERACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950101', 'Clases de cobros por actividades de operaciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('95010101', 'Cobros procedentes de las ventas de bienes y prestaciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n de servicios', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('95010102', 'Cobros procedentes de regalÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â­as, cuotas, comisiones y otros ingresos de actividades ordinarias', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('95010103', 'Cobros procedentes de contratos mantenidos con propÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³sitos de intermediaciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('95010104', 'Cobros procedentes de primas y prestaciones, anualidades y otros beneficios de pÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³lizas suscritas', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('95010105', 'Otros cobros por actividades de operaciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950102', 'Clases de pagos por actvidades de operaciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('95010201', 'Pagos a proveedores por el suministro de bienes y servicios', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('95010202', 'Pagos procedentes de contratos mantenidos para intermediaciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n o para negociar', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('95010203', 'Pagos a y por cuenta de los empleados', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('95010204', 'Pagos por primas y prestaciones, anualidades y otras obligaciones derivadas de las pÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³lizas suscritas', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('95010205', 'Otros pagos por actividades de operaciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950103', 'Dividendos pagados', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950104', 'Dividendos recibidos', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950105', 'Intereses pagados', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950106', 'Intereses recibidos', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950107', 'Impuestos a las ganancias pagados', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950108', 'Otras entradas (salidas) de efectivo', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9502', 'FLUJOS DE EFECTIVO PROCEDENTES DE (UTILIZADOS EN) ACTIVIDADES DE INVERSIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950201', 'Efectivo procedentes de la venta de acciones en subsidiarias u otros negocios', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950202', 'Efectivo utilizado para adquirir acciones en subsidiarias u otros negocios para tener el control', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950203', 'Efectivo utilizado en la compra de participaciones no controladoras', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950204', 'Otros cobros por la venta de acciones o instrumentos de deuda de otras entidades', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950205', 'Otros pagos para adquirir acciones o instrumentos de deuda de otras entidades', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950206', 'Otros cobros por la venta de participaciones en negocios conjuntos', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950207', 'Otros pagos para adquirir participaciones en negocios conjuntos', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950208', 'Importes procedentes por la venta de propiedades, planta y equipo', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950209', 'Adquisiciones de propiedades, planta y equipo', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950210', 'Importes procedentes de ventas de activos intangibles', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950211', 'Compras de activos intangibles', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950212', 'Importes procedentes de otros activos a largo plazo', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950213', 'Compras de otros activos a largo plazo', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950214', 'Importes procedentes de subvenciones del gobierno', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950215', 'Anticipos de efectivo efectuados a terceros', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950216', 'Cobros procedentes del reembolso de anticipos y prÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©stamos concedidos a terceros', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950217', 'Pagos derivados de contratos de futuro, a tÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©rmino, de opciones y de permuta financiera', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950218', 'Cobros procedentes de contratos de futuro, a tÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©rmino, de opciones y de permuta financiera', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950219', 'Dividendos recibidos', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950220', 'Intereses recibidos', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950221', 'Otras entradas (salidas) de efectivo', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9503', 'FLUJOS DE EFECTIVO PROCEDENTES DE (UTILIZADOS EN) ACTIVIDADES DE FINANCIACIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950301', 'Aporte en efectivo por aumento de capital', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950302', 'Financiamiento por emisiÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n de tÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â­tulos valores', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950303', 'Pagos por adquirir o rescatar las acciones de la entidad', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950304', 'FinanciaciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n por prÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©stamos a largo plazo', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950305', 'Pagos de prÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©stamos', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950306', 'Pagos de pasivos por arrendamientos financieros', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950307', 'Importes procedentes de subvenciones del gobierno', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950308', 'Dividendos pagados', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950309', 'Intereses recibidos', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950310', 'Otras entradas (salidas) de efectivo', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9504', 'EFECTOS DE LA VARIACION EN LA TASA DE CAMBIO SOBRE EL EFECTIVO Y EQUIVALENTES AL EFECTIVO', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('950401', 'Efectos de la variaciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n en la tasa de cambio sobre el efectivo y equivalentes al efectivo', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9505', 'INCREMENTO (DISMINUCIÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œN) NETO DE EFECTIVO Y EQUIVALENTES AL EFECTIVO', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9506', 'EFECTIVO Y EQUIVALENTES AL EFECTIVO AL PRINCIPIO DEL PERIODO', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9507', 'EFECTIVO Y EQUIVALENTES AL EFECTIVO AL FINAL DEL PERIODO', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('96', 'GANANCIA (PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°RDIDA) ANTES DE 15% A TRABAJADORES E IMPUESTO A LA RENTA', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('97', 'AJUSTE POR PARTIDAS DISTINTAS AL EFECTIVO:', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9701', 'Ajustes por gasto de depreciaciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n y amortizaciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9702', 'Ajustes por gastos por deterioro (reversiones por deterioro) reconocidas en los resultados del periodo', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9703', 'PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©rdida (ganancia) de moneda extranjera no realizada', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9704', 'PÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©rdidas en cambio de moneda extranjera', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9705', 'Ajustes por gastos en provisiones', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9706', 'Ajuste por participaciones no controladoras', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9707', 'Ajuste por pagos basados en acciones', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9708', 'Ajustes por ganancias (pÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©rdidas) en valor razonable', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9709', 'Ajustes por gasto por impuesto a la renta', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9710', 'Ajustes por gasto por participaciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n trabajadores', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9711', 'Otros ajustes por partidas distintas al efectivo', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('98', 'CAMBIOS EN ACTIVOS Y PASIVOS:', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9801', '(Incremento) disminuciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n en cuentas por cobrar clientes', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9802', '(Incremento) disminuciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n en otras cuentas por cobrar', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9803', '(Incremento) disminuciÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â³n en anticipos de proveedores', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9804', '(Incremento) disminucion en inventarios', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9805', '(Incremento) disminucion en otros activos', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9806', 'Incremento  (disminucion) en cuentas por pagar comerciales', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9807', 'Incremento  (disminucion) en otras cuentas por pagar', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9808', 'Incremento  (disminucion) en beneficios empleados', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9809', 'Incremento  (disminucion) en anticipos de clientes', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9810', 'Incremento  (disminucion) en otros pasivos', '', '', '9', NULL, 0, 1);
INSERT INTO `billing_contacuentasplan` VALUES ('9820', 'Flujos de efectivo netos procedentes de (utilizados en) actividades de operacion', NULL, NULL, '9', NULL, 0, 1);

/*FIN INGRESAR EL PLAN DE CUENTAS COPLETO*/


/* CONFIGURACION DE CUENTAS******************************************************* */
INSERT INTO `billing_contaconfigcuentas` VALUES ('001', 'Transporte en Compras', 'Para cargar a una cuenta contable el valor del transporte en una factura de compra', '52011501', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('002', 'Otros gastos en Compras', 'Para cargar a una cuenta contable el valor del otros gastos en una factura de compra', '52011501', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('003', 'Iva en Compras', 'Iva pagado en compras', '101050101', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('004', 'Ice en Compras', 'Ice en compras', '101', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('005', 'Imp. verde en compras', 'Impuesto verde en compras', '1010203', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('006', 'Iva en Ventas', 'Iva en Ventas', '201070103', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('007', 'Venta Servicios', 'por servicios vendidos', '4102', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('008', 'Venta Bienes', 'Venta de mercaderia bienes..', '4101', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('009', 'Ice en Ventas', NULL, '1010201', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('010', 'Imp Verde en Ventas', NULL, '101', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('011', 'Anticipos Clientes', 'Cuando se reciben anticipos de los clientes', '20110', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('012', 'Anticipos Proveedores', NULL, '1010403', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('013', 'Cheques Custodio', NULL, '10102060103', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('015', 'Tarj. Cred. Custodio', NULL, '10102060102', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('016', 'Retencion Ventas', 'Cuando hay una retencion', '101050202', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('017', '(Sin Uso)Retencion Iva Ventas', 'Se esta usando una sola cuenta para retenciones Fuente-Iva', '101050102', 0);
INSERT INTO `billing_contaconfigcuentas` VALUES ('018', 'Retencion Compras', NULL, '201070101', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('019', '(Sin Uso)Retencion Iva Compras', 'Se esta usando una sola cuenta para retenciones Fuente-Iva', '201070102', 0);
INSERT INTO `billing_contaconfigcuentas` VALUES ('020', 'Costo Ventas Bienes', NULL, '51', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('021', 'Inventario', 'contra costo venta bienes', '1010306', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('022', 'Compra de Servicios', 'cuenta para el asiento contable cuando se compra servicios, se usa tambien en ajustes de entrada', '1010306', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('023', 'Devolucion en Ventas', 'sadf', '101010102', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('024', 'Devolucion iva ventas', NULL, '101010103', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('025', 'Ajuste Entrada', NULL, '101010103', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('026', 'Compra de Bienes', 'Compra de bienes ... Usada en los ajuste de entrada', '101010103', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('027', 'Intereses Ganados', NULL, '10101', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('028', 'Intereses Pagados', NULL, '101010101', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('029', 'Cuentas x pagar proveedores', 'Cuentas x pagar proveedores', '201030101', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('030', 'Cuentas x cobrar clientes', 'Cobro de cuentas x cobrar', '101010102', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('031', 'Efectivo/Caja', 'Efectivo/Caja', '10101', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('032', 'Nota Credito Compras', NULL, '10101', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('033', 'Devolucion ICE ventas', NULL, '10101', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('034', 'Descuento en Ventas', NULL, '10101', 1);
INSERT INTO `billing_contaconfigcuentas` VALUES ('035', 'Recargo en Ventas', NULL, '10101', 1);
