INSERT INTO `billing_productogrupo` VALUES (108, 'ACCESORIOS VARIOS', 'n', 1, 3, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (109, 'AUDIFONOS', 'n', 1, 6, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (110, 'BATERIAS', 'n', 1, 6, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (111, 'CABLES', 'n', 1, 1, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (112, 'CAMARAS/WEBCAM/FILMADORASS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (113, 'CARGADORES DE CORRIENTE', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (114, 'CARTUCHOS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (115, 'CASE/CHASIS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (116, 'TELEFONOS/CELULARES', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (117, 'CINTAS IMPRESORAS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (118, 'COMPUTADORAS/SERVIDORES', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (119, 'DISCOS DUROS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (120, 'UNIDAD DVD/DVD PLAYERS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (121, 'OPTICOS DVD Y CD BLANCO', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (122, 'ELECTRODOMESTICOS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (123, 'ESCANERS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (124, 'FLASH MEMORY', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (125, 'FUENTE DE PODER', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (126, 'GAMES VOLANTES / VIDEOJUEGOS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (127, 'IMPRESORAS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (128, 'JUGUETES', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (129, 'KIT LIMPIEZA /ASPIRADORAS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (130, 'LECTORES MEMORIA', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (131, 'MEMORIAS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (132, 'MESAS Y SILLAS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (133, 'MINIHUB / BLUETOOTH', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (134, 'MOCHILAS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (135, 'ESTUCHES', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (136, 'MONITORES', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (137, 'MOTHERBOARDS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (138, 'MOUSE / MINIMOUSE', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (139, 'MP4 /MP3/ IPODS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (140, 'PANTALLAS PROYECCION', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (141, 'PARLANTES', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (142, 'PORTATILES', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (143, 'PROCESADORES', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (144, 'PROYECTORES', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (145, 'RACKS DISCOS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (147, 'REDES /EQUIPOS INTERNET', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (148, 'REFILER /POLVO LASER/ PAPEL FOTO', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (149, 'REGULADORES / SUPRESORES', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (152, 'REPUESTOS COMPUHELP', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (153, 'SNACKS', 'n', 0, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (154, 'SOFTWARE', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (155, 'SOPORTES PARED Y TECHO', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (156, 'TABLETS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (157, 'TARJETAS SONIDO/VIDEO/TV', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (158, 'TECLADOS', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (159, 'TELEVISORES', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (160, 'TONER LASER', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (161, 'UPS ENERGIA', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (162, 'VENTILADORES ', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (163, 'MATERIAL PUBLICITARIO', 'n', 1, 0, 1, 0);
INSERT INTO `billing_productogrupo` VALUES (164, 'SERVICIOS', 'SERVICIOS VARIOS', 0, 6, 1, 0);
